### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by dennis777** [Abhisheklearn12/Multi_threaded_reverse_proxy#1]
I compiled the program on my macOS machine with `clang reverse_proxy.c -o reverse_proxy` and ran it `./reverse_proxy`

going to the localhost address yields the following error in safari
<img width="616" alt="image" src="https://github.com/user-attachments/assets/e48563a4-ed6d-4144-b1d7-0492b519c305" />

I made sure the file exists at my path that I have in the code 
`ls -l /Users/dennis/Documents/Xcode/C/Multi_threaded_reverse_proxy/index.html`

And made sure content length is correct 
`wc -c /Users/dennis/Documents/Xcode/C/Multi_threaded_reverse_proxy/index.html` -> `391 ...`

running `curl localhost:8080/index.html` yields the following response 
`curl: (56) Recv failure: Connection reset by peer`

Here is verbose output
```
dennis@Denniss-MacBook-Pro C % curl -v localhost:8080/index.html
* Host localhost:8080 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:8080...
* connect to ::1 port 8080 from ::1 port 53036 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080
> GET /index.html HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.7.1
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: text/html
< Content-Length: 391
< 
* Recv failure: Connection reset by peer
* Closing connection
curl: (56) Recv failure: Connection reset by peer
```

Why the issue how can it be fixed? I'm new to C trying to learn it

**Comment by dennis777** [comment]
After some research trial and error I added `shutdown()` before we close the socket connection and that allows curl to receive the html response properly, but safari still doesn't load the html file

```c
// Updated handle_client function
void *handle_client(void *args) {
    //...
    send(client_sock, response_header, strlen(response_header), 0);
    send(client_sock, file_buffer, file_size, 0);

    // Clean up and close the connection
    shutdown(client_sock, SHUT_WR); // <-- Added here
    close(client_sock);
    free(client_args);

    return NULL;
}
```

**Comment by dennis777** [comment]
Actually still doesn't show the index.html page on safari, only curl works

**Comment by dennis777** [comment]
Turns out it was placing a https in the url instead of http :) All works as intended, I think maybe update the code to include the `shutdown()` since that fixed it for me @abhilash1213

**Comment by Abhisheklearn12** [comment]
thanks bro for putting effort in making this code great, will update after exams. Great work dennis777, appreciate your effort.
